# -*- coding: utf-8 -*-
"""driver_behavior_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dp0pRXGiONF_65dDNvqCq3WeD3LAits3

***Objective***

The primary objective of this project is to develop a deep learning-based image classification model that can automatically detect and classify different driver behaviors. The system aims to distinguish between safe driving and various distracted behaviors such as texting, calling, or turning away from the road.

By leveraging Convolutional Neural Networks (CNNs) like VGG16, MobileNet and AlexNet, the model learns visual patterns associated with each behavior category. The goal is to achieve high classification accuracy and reliable real-time performance.
"""

# importing necessary libraries

import os
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

import tensorflow as tf
from tensorflow.keras import layers, models

import kagglehub
from pathlib import Path
import hashlib
import cv2
from PIL import Image

!pip install kaggle

"""### Data Reading from kaggle"""

path = kagglehub.dataset_download("robinreni/revitsone-5class")

print("Path to dataset files:", path)

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

dataset_path = "/root/.cache/kagglehub/datasets/robinreni/revitsone-5class/versions/1/revitsone-5classes/Revitsone-5classes"
dataset_path = Path(dataset_path)
for folder in os.listdir(dataset_path):
    print(folder)

# Create a dataset from the image folders
data = tf.keras.preprocessing.image_dataset_from_directory(
    dataset_path,
    image_size=(256, 256),
    batch_size=32
)

class_names = data.class_names
print("Classes:", class_names)

plt.figure(figsize=(12,8))
for images_batch, labels_batch in data.take(10):
    for i in range(9):
        plt.subplot(3,3,i+1)
        plt.imshow(images_batch[i].numpy().astype("uint8"))
        plt.title(class_names[labels_batch[i]])
        plt.axis("off")

"""## Dataset Preparation

The dataset consists of five image classes stored in separate folders.
Each folder represents one class label.

Before training, the dataset was cleaned by verifying all image files using PIL.
Corrupted or unreadable images were removed to prevent runtime decoding errors
during model training.

The dataset was then split using stratified sampling into:

- 70% Training set
- 10% Validation set
- 20% Test set

Stratification ensures that each split maintains the same class distribution.
The test set was kept completely unseen during training and model selection.

### Checking for duplicates
"""

def get_file_hash(filepath):
  hash_md5 = hashlib.md5()
  with open(filepath, "rb") as f:
       for chunk in iter(lambda: f.read(4096), b""):
            hash_md5.update(chunk)
  return hash_md5.hexdigest()

hashes = {}
duplicates = []
total_images = 0

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(('.png', '.jpg', '.jpeg')):
            total_images += 1
            filepath = os.path.join(root, file)
            file_hash = get_file_hash(filepath)

            if file_hash in hashes:
                duplicates.append((filepath, hashes[file_hash]))
            else:
                hashes[file_hash] = filepath

print("Total images:", total_images)
print("Number of duplicate images:", len(duplicates))
print("Number of hashes images:", len(hashes))

"""### Checking for unreadable images"""

bad_files = []

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(('.png', '.jpg', '.jpeg')):
            filepath = os.path.join(root, file)
            img = cv2.imread(filepath)
            if img is None:
                bad_files.append(filepath)

print("Unreadable images:", len(bad_files))

for file in bad_files[:5]:   # show first 5
    try:
        img = Image.open(file)
        plt.imshow(img)
        plt.title("Corrupted Image")
        plt.axis("off")
        plt.show()
    except Exception as e:
        print("Cannot display:", file)
        print("Error:", e)

for file in bad_files:
    os.remove(file)

print("Corrupted images removed.")

labels = sorted([d.name for d in dataset_path.iterdir() if d.is_dir()])
num_classes = len(labels)

class_to_id = {name: idx for idx, name in enumerate(labels)}
class_to_id

all_files = []
all_labels = []

for cname in labels:
    class_dir = dataset_path / cname
    files = [
        str(f) for f in class_dir.glob("*")
        if f.suffix.lower() in [".jpg", ".jpeg", ".png"]
    ]

    all_files.extend(files)
    all_labels.extend([class_to_id[cname]] * len(files))

all_files = np.array(all_files)
all_labels = np.array(all_labels)

print("Total images:", len(all_files))

import os, random
SEED = 42
tf.random.set_seed(SEED)
np.random.seed(SEED)
random.seed(SEED)

# Test split (20%)
x_trainval, x_test, y_trainval, y_test = train_test_split(
    all_files,
    all_labels,
    test_size=0.20,
    stratify=all_labels,
    random_state=SEED
)

# Validation split (10% of total = 12.5% of trainval)
x_train, x_val, y_train, y_val = train_test_split(
    x_trainval,
    y_trainval,
    test_size=0.125,
    stratify=y_trainval,
    random_state=SEED
)

print(f"Train: {len(x_train)} ({len(x_train)/len(all_files):.2%})")
print(f"Val:   {len(x_val)} ({len(x_val)/len(all_files):.2%})")
print(f"Test:  {len(x_test)} ({len(x_test)/len(all_files):.2%})")

IMG_SIZE = (224, 224)
BATCH_SIZE = 32
AUTOTUNE = tf.data.AUTOTUNE

# Image loader
def decode_and_resize(path, label):
    img = tf.io.read_file(path)
    img = tf.image.decode_image(img, channels=3, expand_animations=False)
    img = tf.image.resize(img, IMG_SIZE)
    img = tf.cast(img, tf.float32) / 255.0   # baseline normalization
    return img, label

# Dataset builder

def make_ds(paths, labels, training=False):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if training:
        ds = ds.shuffle(1000, seed=SEED)
    ds = ds.map(decode_and_resize, num_parallel_calls=AUTOTUNE)
    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(AUTOTUNE)
    return ds

# Create datasets
train_ds = make_ds(x_train, y_train, training=True)
val_ds   = make_ds(x_val, y_val)
test_ds  = make_ds(x_test, y_test)

"""### Data Augmentation"""

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.1),
    tf.keras.layers.RandomZoom(0.1),
    tf.keras.layers.RandomContrast(0.1)
])

def make_ds(paths, labels, training=False):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    if training:
        ds = ds.shuffle(1000, seed=SEED)

    ds = ds.map(decode_and_resize, num_parallel_calls=AUTOTUNE)

    if training:
        ds = ds.map(lambda x, y: (data_augmentation(x, training=True), y),
                    num_parallel_calls=AUTOTUNE)

    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(AUTOTUNE)

    return ds



"""# Baseline CNN

## Baseline Convolutional Neural Network (CNN)

A simple CNN was implemented as a baseline model.
This model was trained from scratch without any pretrained weights.

Architecture:
- 3 Convolutional blocks (Conv + BatchNorm + ReLU + MaxPooling)
- Global Average Pooling
- Dense layer with Dropout
- Softmax output layer

Images were normalized by scaling pixel values to the range [0,1].

The purpose of this baseline model is to evaluate performance without
transfer learning and to serve as a comparison benchmark for pretrained models.
"""

baseline_model = models.Sequential([
    layers.Input(shape=(224, 224, 3)),

    layers.Conv2D(32, 3, padding="same"),
    layers.BatchNormalization(),
    layers.Activation("relu"),
    layers.MaxPooling2D(),

    layers.Conv2D(64, 3, padding="same"),
    layers.BatchNormalization(),
    layers.Activation("relu"),
    layers.MaxPooling2D(),

    layers.Conv2D(128, 3, padding="same"),
    layers.BatchNormalization(),
    layers.Activation("relu"),
    layers.MaxPooling2D(),

    layers.GlobalAveragePooling2D(),  # better than Flatten
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.5),

    layers.Dense(num_classes, activation="softmax")
])

baseline_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

baseline_model.summary()

callback = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=2,
    restore_best_weights=True
)

EPOCHS = 10

history = baseline_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    callbacks=[callback]
)

test_loss, test_acc = baseline_model.evaluate(test_ds)
print(f"Baseline Test Accuracy: {test_acc:.4f}")

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='train')
plt.plot(history.history['val_accuracy'], label='val')
plt.title("Accuracy")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='train')
plt.plot(history.history['val_loss'], label='val')
plt.title("Loss")
plt.legend()

plt.show()

"""## VGG16 Transfer Learning

To improve performance, transfer learning was applied using the pretrained
VGG16 model trained on ImageNet.

Two training phases were used:

1. Feature Extraction:
   - The convolutional base was frozen.
   - Only the custom classification head was trained.

2. Fine-Tuning:
   - The deeper convolutional layers were unfrozen.
   - A smaller learning rate was used.
   - This allowed the model to adapt pretrained features to the target dataset.

VGG16-specific preprocessing was applied to match ImageNet training conditions.
"""

from tensorflow.keras.applications.vgg16 import preprocess_input

def decode_and_resize_vgg(path, label):
    img = tf.io.read_file(path)
    img = tf.image.decode_image(img, channels=3, expand_animations=False)
    img = tf.image.resize(img, IMG_SIZE)
    img = preprocess_input(img)   # VGG16 preprocessing
    return img, label

def make_ds_vgg(paths, labels, training=False):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if training:
        ds = ds.shuffle(1000, seed=SEED)
    ds = ds.map(decode_and_resize_vgg, num_parallel_calls=AUTOTUNE)
    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(AUTOTUNE)
    return ds

train_ds_vgg = make_ds_vgg(x_train, y_train, training=True)
val_ds_vgg   = make_ds_vgg(x_val, y_val)
test_ds_vgg  = make_ds_vgg(x_test, y_test)

"""Load VGG16 backbone (frozen)"""

from tensorflow.keras.applications import VGG16
vgg_base = VGG16(
    weights="imagenet",
    include_top=False,
    input_shape=(224, 224, 3)
)

vgg_base.trainable = False

vgg_model = models.Sequential([
    vgg_base,

    layers.GlobalAveragePooling2D(),
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.5),

    layers.Dense(num_classes, activation="softmax")
])

vgg_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=3,
        restore_best_weights=True
    )
]

vgg_model.summary()

EPOCHS = 10

history_vgg = vgg_model.fit(
    train_ds_vgg,
    validation_data=val_ds_vgg,
    epochs=EPOCHS,
    callbacks=callbacks
)

test_loss, test_acc = vgg_model.evaluate(test_ds_vgg)
print(f"VGG16 Test Accuracy: {test_acc:.4f}")

fig, ax = plt.subplots(1, 2, figsize=(14,5))

# Accuracy
ax[0].plot(history_vgg.history['accuracy'], label='Train Accuracy')
ax[0].plot(history_vgg.history['val_accuracy'], label='Validation Accuracy')
ax[0].set_title('VGG16 Accuracy')
ax[0].set_xlabel('Epoch')
ax[0].set_ylabel('Accuracy')
ax[0].legend()
ax[0].grid(True)

# Loss
ax[1].plot(history_vgg.history['loss'], label='Train Loss')
ax[1].plot(history_vgg.history['val_loss'], label='Validation Loss')
ax[1].set_title('VGG16 Loss')
ax[1].set_xlabel('Epoch')
ax[1].set_ylabel('Loss')
ax[1].legend()
ax[1].grid(True)

plt.show()

"""### Fine-tuning"""

vgg_base.trainable = True

# Freeze first 3 blocks
for layer in vgg_base.layers[:15]:
    layer.trainable = False

vgg_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

history_finetune = vgg_model.fit(
    train_ds_vgg,
    validation_data=val_ds_vgg,
    epochs=10,
    callbacks=callbacks
)

test_loss_ft, test_acc_ft = vgg_model.evaluate(test_ds_vgg)
print(f"VGG16 Fine-tuned Test Accuracy: {test_acc_ft:.4f}")
print(f"VGG16 Fine-tuned Test Loss: {test_loss_ft:.4f}")

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
plt.plot(history_finetune.history['accuracy'], label='train')
plt.plot(history_finetune.history['val_accuracy'], label='val')
plt.title("VGG16 Fine-tuned Accuracy")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history_finetune.history['loss'], label='train')
plt.plot(history_finetune.history['val_loss'], label='val')
plt.title("VGG16 Fine-tuned Loss")
plt.legend()

plt.show()

"""## MobileNetV2 Transfer Learning

MobileNetV2, a lightweight architecture optimized for efficiency,
was also evaluated using transfer learning.

Similar to VGG16, the model was trained in two stages:
- Frozen feature extraction
- Fine-tuning with a lower learning rate

MobileNetV2 uses depthwise separable convolutions, which significantly
reduce the number of parameters compared to traditional CNN architectures.
"""

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

def decode_and_resize_mobilenet(path, label):
    img = tf.io.read_file(path)
    img = tf.image.decode_image(img, channels=3, expand_animations=False)
    img = tf.image.resize(img, IMG_SIZE)
    img = preprocess_input(img)  # scales to [-1, 1]
    return img, label

def make_ds_mobilenet(paths, labels, training=False):
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))
    if training:
        ds = ds.shuffle(1000, seed=SEED)
    ds = ds.map(decode_and_resize_mobilenet, num_parallel_calls=AUTOTUNE)
    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(AUTOTUNE)
    return ds

train_ds_m = make_ds_mobilenet(x_train, y_train, training=True)
val_ds_m   = make_ds_mobilenet(x_val, y_val)
test_ds_m  = make_ds_mobilenet(x_test, y_test)

"""### Load MobileNetV2 Backbone (Frozen First)"""

from tensorflow.keras.applications import MobileNetV2

mobilenet_base = MobileNetV2(
    weights="imagenet",
    include_top=False,
    input_shape=(224, 224, 3)
)

mobilenet_base.trainable = False  # feature extraction first

mobilenet_model = tf.keras.Sequential([
    mobilenet_base,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(num_classes, activation="softmax")
])

mobilenet_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor="val_loss",
        patience=3,
        restore_best_weights=True
    )
]

history_mobilenet = mobilenet_model.fit(
    train_ds_m,
    validation_data=val_ds_m,
    epochs=10,
    callbacks=callbacks
)

"""Fine-tuning"""

# Unfreeze part of the model.

mobilenet_base.trainable = True

# Freeze first 100 layers (keep early features stable)
for layer in mobilenet_base.layers[:100]:
    layer.trainable = False

# Recompile with lower LR.

mobilenet_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

history_mobilenet_ft = mobilenet_model.fit(
    train_ds_m,
    validation_data=val_ds_m,
    epochs=10,
    callbacks=callbacks
)

test_loss_m, test_acc_m = mobilenet_model.evaluate(test_ds_m)
print(f"MobileNetV2 Test Accuracy: {test_acc_m:.4f}")

plt.figure(figsize=(12,4))

plt.subplot(1,2,1)
plt.plot(history_mobilenet_ft.history['accuracy'], label='train')
plt.plot(history_mobilenet_ft.history['val_accuracy'], label='val')
plt.title("MobileNetV2 Fine-tuned Accuracy")
plt.legend()

plt.subplot(1,2,2)
plt.plot(history_mobilenet_ft.history['loss'], label='train')
plt.plot(history_mobilenet_ft.history['val_loss'], label='val')
plt.title("MobileNetV2 Fine-tuned Loss")
plt.legend()

plt.show()

"""## AlexNet

AlexNet is a deep learning model that made a big impact in image recognition. It became famous for its ability to classify images accurately. It won the ImageNet Large Scale Visual Recognition Challenge (ILSVRC) 2012 with a top-5 error rate of 15.3% (beating the runner up which had a top-5 error rate of 26.2%).


**AlexNet Architecture**

Its architecture includes:

* 5 convolutional layers with Max-Pooling applied after the 1st, 2nd and 5th layers to enhance feature extraction.

* Overlapping Max-Pooling uses a 3×3 filter with stride 2 which improved performance by reducing top-1 error by 0.4% and top-5 error by 0.3% compared to non-overlapping pooling.

* Followed by 2 fully connected layers each using dropout to prevent overfitting.

* Ends with a softmax layer for final classification.
"""

IMG_SIZE = (224, 224, 3)
NUM_CLASSES = 5

def AlexNet(input_shape=IMG_SIZE, num_classes=NUM_CLASSES):
    model = models.Sequential()

    # Conv Layer 1
    model.add(layers.Conv2D(96, kernel_size=11, strides=4, activation='relu', input_shape=input_shape))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(pool_size=3, strides=2))

    # Conv Layer 2
    model.add(layers.Conv2D(256, kernel_size=5, padding='same', activation='relu'))
    model.add(layers.BatchNormalization())
    model.add(layers.MaxPooling2D(pool_size=3, strides=2))

    # Conv Layer 3
    model.add(layers.Conv2D(384, kernel_size=3, padding='same', activation='relu'))

    # Conv Layer 4
    model.add(layers.Conv2D(384, kernel_size=3, padding='same', activation='relu'))

    # Conv Layer 5
    model.add(layers.Conv2D(256, kernel_size=3, padding='same', activation='relu'))
    model.add(layers.MaxPooling2D(pool_size=3, strides=2))

    # Flatten
    model.add(layers.Flatten())

    # Fully connected layers
    model.add(layers.Dense(1024, activation='relu'))
    model.add(layers.Dropout(0.5))
    model.add(layers.Dense(1024, activation='relu'))
    model.add(layers.Dropout(0.5))
    model.add(layers.Dense(num_classes, activation='softmax'))

    return model

model_Alex = AlexNet()
model_Alex.summary()

tf.keras.utils.plot_model(
    model_Alex,
    to_file='alex_model.png',
    show_shapes=True,
    show_layer_names=True,
    show_layer_activations=True,
    dpi=80
)

model_Alex.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])

model_Alex.summary()

history_alex = model_Alex.fit(train_ds,
                         epochs=20, validation_data = val_ds)

import matplotlib.pyplot as plt

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(history_alex.history['loss'])
plt.plot(history_alex.history['val_loss'])
plt.title("Loss")

plt.subplot(1,2,2)
plt.plot(history_alex.history['accuracy'])
plt.plot(history_alex.history['val_accuracy'])
plt.title("Accuracy")

test_loss, test_acc = model_Alex.evaluate(test_ds)
print(f"Test Accuracy: {test_acc:.4f}")
print(f"Test Loss: {test_loss:.4f}")

"""### All model's accuracy"""

# Baseline
test_loss_base, test_acc_base = baseline_model.evaluate(test_ds)
print(f" Baseline model: Test accuracy-{test_acc_base}, Test loss-{test_loss_base} ")

# VGG16
test_loss_vgg, test_acc_vgg = vgg_model.evaluate(test_ds_vgg)
print(f" VGG16 model: Test accuracy-{test_acc_vgg}, Test loss-{test_loss_vgg} ")

# MobileNet
test_loss_mob, test_acc_mob = mobilenet_model.evaluate(test_ds_m)
print(f" MobileNet model: Test accuracy-{test_acc_mob}, Test loss-{test_loss_mob} ")

# AlexNet
test_loss_alex, test_acc_alex = model_Alex.evaluate(test_ds)
print(f" AlexNet model: Test accuracy-{test_acc_alex}, Test loss-{test_loss_alex} ")

import pandas as pd

results = {
    "Model": ["Baseline CNN", "VGG16 (Fine-tuned)", "MobileNetV2 (Fine-tuned)", "AlexNet"],
    "Test Accuracy": [
        round(test_acc_base, 4),
        round(test_acc_vgg, 4),
        round(test_acc_mob, 4),
        round(test_acc_alex, 4)
    ],
    "Test Loss": [
        round(test_loss_base, 4),
        round(test_loss_vgg, 4),
        round(test_loss_mob, 4),
        round(test_loss_alex, 4)
    ]
}

results_df = pd.DataFrame(results)
results_df.sort_values("Test Accuracy", ascending=False)

"""## Model Comparison

The performance of the four models was compared using test accuracy and
number of parameters.

Observations:
- The baseline CNN achieved moderate accuracy but showed signs of underfitting.
- VGG16 significantly improved performance due to pretrained feature extraction.
- MobileNetV2 achieved competitive or superior accuracy while using fewer parameters.
- AlexNet achieved competitive accuracy. Larger number of parameters, slower training compared to MobileNet.

These results demonstrate the effectiveness of transfer learning for
image classification tasks with limited datasets.

## Testing on New Image
"""

import requests
from PIL import Image

url = 'https://thumbs.dreamstime.com/b/transportation-vehicle-people-concept-male-car-driver-looking-passenger-back-seat-273571683.jpg'

filename = "driver_test.jpg"

response = requests.get(url)
with open(filename, "wb") as f:
    f.write(response.content)

img = Image.open("driver_test.jpg")
plt.imshow(img)
plt.axis("off")
plt.show()

from tensorflow.keras.preprocessing import image

def preprocess_image(img_path):
    img = image.load_img(img_path, target_size=IMG_SIZE)
    img_array = image.img_to_array(img)
    img_array = img_array / 255.0          # normalize
    img_array = np.expand_dims(img_array, axis=0)  # add batch dimension
    return img_array

img_path = "driver_test.jpg"

processed_img = preprocess_image(img_path)

"""### VGG model prediction"""

#VGG_model predictions
prediction_vgg = vgg_model.predict(processed_img)
print("Raw prediction:", prediction_vgg)

predicted_class = np.argmax(prediction_vgg)
confidence = np.max(prediction_vgg)

print("Predicted Class:", class_names[predicted_class])
print("Confidence:", confidence)

"""### Mobilenet model prediction"""

#mobilenet_model predictions
prediction_mobile = mobilenet_model.predict(processed_img)
print("Raw prediction:", prediction_mobile)

predicted_class = np.argmax(prediction_mobile)
confidence = np.max(prediction_mobile)

print("Predicted Class:", class_names[predicted_class])
print("Confidence:", confidence)

"""### Alex_model prediction"""

#Alex_model predictions
prediction_alex = model_Alex.predict(processed_img)

print("Raw prediction:", prediction_alex)

predicted_class = np.argmax(prediction_alex)
confidence = np.max(prediction_alex)

print("Predicted Class:", class_names[predicted_class])
print("Confidence:", confidence)

"""**Results**

* VGG16 and AlexNet models misclassified this image.

* MobileNet is able to classify correctly.

## Testing on Another Image

* Ckeck for the different another image.
"""

url = 'https://youngpeopletoday.net/wp-content/uploads/2022/11/images3937-637b7d9d5d65d.jpg'

img = "car_driver.jpg"

response = requests.get(url)
with open(img, "wb") as f:
    f.write(response.content)

img = Image.open("car_driver.jpg")
plt.imshow(img)
plt.axis("off")
plt.show()

"""### VGG model prediction"""

img='car_driver.jpg'
processed_img = preprocess_image(img)

vgg_prediction = vgg_model.predict(processed_img)

print("Raw prediction:", vgg_prediction)

predicted_class = np.argmax(vgg_prediction)
confidence = np.max(vgg_prediction)

print("Predicted Class:", class_names[predicted_class])
print("Confidence:", confidence)

"""### MobileNet model prediction"""

mobile_prediction = mobilenet_model.predict(processed_img)

print("Raw prediction:", mobile_prediction)

predicted_class = np.argmax(mobile_prediction)
confidence = np.max(mobile_prediction)

print("Predicted Class:", class_names[predicted_class])
print("Confidence:", confidence)

"""### Alex model prediction"""

alex_prediction = model_Alex.predict(processed_img)

print("Raw prediction:", alex_prediction)

predicted_class = np.argmax(alex_prediction)
confidence = np.max(alex_prediction)

print("Predicted Class:", class_names[predicted_class])
print("Confidence:", confidence)

"""**Result**

* VGG16 model misclassified the image.

* AlexNet and MobileNet models are able to classify the image correctly.

* VGG16 model seems like overfitted(learned dataset very much) and finding difficulty to classify a new image .

## Conclusion

* This experiment demonstrates that transfer learning substantially improves
image classification performance compared to training a CNN from scratch.

* Pretrained models such as VGG16 and MobileNetV2, AlexNet leverage learned representations
from large-scale datasets (ImageNet), enabling better generalization.

* Among them, VGG16 achieved the highest accuracy, demonstrating superior feature extraction capability and classification performance on the given dataset.

* However, testing on completely new external images revealed some performance variation. This highlights the importance of dataset diversity and real-world variability in improving generalization.

* Future improvements may include stronger data augmentation and expanding the dataset with more diverse driving conditions.

* Overall, this project demonstrates that deep learning techniques can effectively classify driver behaviors and can serve as a foundation for real-time Driver Monitoring Systems. Such systems have significant potential to reduce road accidents by detecting and alerting unsafe driving activities
"""

